# -*- encoding: utf-8 -*-
import slabs_process_control_sheet
import tcv_mrp_gangsaw_summary
import tcv_mrp_abrasive_durability
import tcv_mrp_anual_report
import tcv_mrp_in_process
import tcv_production_rates
import tcv_mrp_supplies_by_product
import tcv_mrp_blade_yield
import tcv_mrp_days_lapses
import tcv_mrp_gangsaw_by_hardness
import tcv_mrp_gangsaw_order
import tcv_mrp_gangsaw_control_form

